repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: elastic
  url: https://helm.elastic.co

releases:
- name: metrics-server
  chart: stable/metrics-server
  namespace: kube-system
  condition: metrics-server.enabled
  set:
  - name: kubelet-insecure-tls
    value: true
  - name: kubelet-preferred-address-types
    value: InternalIP
- name: prometheus-operator
  chart: stable/prometheus-operator
  namespace: monitoring
  disableValidation: true
- name: elasticsearch
  namespace: monitoring
  chart: elastic/elasticsearch
  values:
  - elasticsearch.yaml
- name: logstash
  namespace: monitoring
  chart: elastic/logstash
  values:
  - logstash.yaml
- name: kibana
  namespace: monitoring
  chart: elastic/kibana
- name: filebeat
  namespace: monitoring
  chart: elastic/filebeat
  values:
  - filebeat.yaml
- name: kafka
  namespace: monitoring
  chart: bitnami/kafka
  values:
  - kafka.yaml
  
environments:
  default:
    values:
    - environments/default/values.yaml